Repository flux3dp/beam-studio, pull requests merged in 2021-06, with the labels that each got.

#122 add path join to fileSystem interface
  src/implementations/fileSystem.ts
  src/implementations/storage.ts
Labels: size/XS

#123 Implement os
  src/implementations/os.ts
Labels: size/XS

#124 handle electron lib
  src/implementations/communicator.ts
  src/implementations/cookies.ts
  src/implementations/fileSystem.ts
  src/implementations/menu.ts
Labels: size/M

#125 Update diode laser naming
  src/implementations/fileSystem.ts
  src/node/menu-resource.js
Labels: size/S

#126 clean the rest require node
  package.json
  src/implementations/menu.ts
  src/implementations/network.ts
  src/implementations/os.ts
  webpack.config.js
  yarn.lock
Labels: size/M

#127 Update version
  package.json
  public/sass/views/_change-log-dialog.scss
Labels: size/XS

#129 add two more functions in communicator
  src/implementations/communicator.ts
Labels: size/XS

#130 move desktop changelog back to its repo
  src/implementations/changelog.ts
Labels: size/M

#131 Reduce app size
  build/clearup-develop-files.bat
  build/clearup-develop-files.sh
  package.json
Labels: size/S

#132 use eventemitter3 which is compatible for both node and browser
  package.json
  yarn.lock
Labels: size/S

#133 Update dialog implementations
  src/implementations/dialog.ts
Labels: size/M

#136 extract menu event listener
  src/implementations/menuEventListenerFactory.ts
Labels: size/XS

#137 create a new script to run webpack watch
  package.json
Labels: size/XS

#139 Fix shadow-window entry file for webpack
  public/shadow-index.html
  src/shadow-window.ts
  webpack.config.js
Labels: size/M

#140 Update translation to match renderer side
  src/node/menu-resource.js
Labels: size/XS

#141 Fix device selector roller style
  README.md
  public/sass/main.scss
  public/sass/views/_device-selector.scss
  public/sass/views/_device_selector.scss
Labels: size/L

#138 move electron-specific code here
  src/electron-menubar-helper.ts
  src/implementations/customMenuActionProvider.ts
  src/implementations/menu.ts
  src/implementations/recentMenuUpdater.ts
  src/loader.ts
  src/main.ts
  src/node/main-window-entry.js
  webpack.config.js
Labels: size/L

#142 Fix change log scroll bar issue in windows
  public/sass/views/_change-log-dialog.scss
Labels: size/XS

#143 Fix imageProcessor MIME_PNG
  src/implementations/imageProcessor.ts
Labels: size/XS

#146 add missing 'remote' field to global electron variable
  src/main.ts
Labels: size/XS

#147 abandon backbone, embrace react router
  package.json
  src/main.ts
  yarn.lock
Labels: size/L

#150 remove electron.version which is duplicate with FLUX.version
  public/index.html
  src/main.ts
  src/node/main-window-entry.js
Labels: size/XS

#151 Add pdf helper implementation
  src/implementations/pdfHelper.ts
Labels: size/M

#152 Update translations
  src/node/menu-resource.js
Labels: size/XS

#153 move electron-specific action here
  package.json
  src/electron-updater.ts
  src/implementations/customMenuActionProvider.ts
  src/implementations/menu.ts
  src/main.ts
  yarn.lock
Labels: size/L

#154 Fix WINDOW_CLOSE event only registered for windows
  src/main.ts
Labels: size/XS

#155 Add getFontName to font implementation
  src/implementations/fontHelper.ts
  src/implementations/fontScanner.ts
Labels: size/M

#156 Update menu
  src/implementations/menu.ts
Labels: size/S
