Repository flux3dp/beam-studio, pull requests merged in 2021-04, with the labels that each got.

#31 remove the cursor once the selected element get deleted
  public/js/lib/svgeditor/svgcanvas.js
Labels: bug

#32 redraw guidelines after canvas size get changed
  src/web/app/actions/beambox.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/preview-mode-background-drawer.ts
  src/web/app/constants/beambox-constants.ts
  src/web/app/dispatcher/beambox-dispatcher.ts
  src/web/app/pages/Beambox.tsx
  src/web/app/stores/beambox-store.ts
Labels: bug

#34 create a CI pipeline to run unit tests on each PR
  .github/workflows/beam-studio-ci.yml
  .gitignore
  jest.config.integration.only.js
  jest.config.js
  jest.config.spec.only.js
  package.json
  src/web/app/action-creators/device.spec.ts
  src/web/app/constants/action-creator-device.ts
  src/web/main.ts
  yarn.lock
Labels: enhancement

#38 incorrect translation
  src/node/menu-resource.js
Labels: bug

#37 support paste_in_place at menu bar
  src/node/menu-manager.js
  src/node/menu-resource.js
  src/web/app/action-creators/device.spec.ts
  src/web/app/action-creators/monitor.spec.ts
  src/web/app/action-creators/monitor.ts
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/constants/action-creator-monitor.ts
Labels: enhancement

#39 混和雷射校正錯誤訊息顯示 #815 [ object Object ]，無法進行校正
  src/web/app/views/beambox/Diode-Calibration.tsx
Labels: bug

#40 Fix autosave when hash is not beambox
  src/web/helpers/auto-save-helper.ts
Labels: bug, enhancement

#43 西班牙版的雷射參數單位多了一個m
  src/web/app/lang/es.ts
Labels: bug

#44 行列輸入框沒有對齊
  public/sass/lang/_de.scss
  public/sass/lang/_en.scss
  public/sass/lang/_es.scss
  src/web/app/views/beambox/Tool-Panels/RowColumn.tsx
Labels: bug

#41 Fix windows tutorial position bug
  src/web/app/actions/beambox/constant.ts
  src/web/app/constants/tutorial-constants.tsx
  src/web/helpers/absolute-position-helper.ts
Labels: bug

#46 Update styles, hide scrollbar
  public/sass/pages/_beambox.scss
  public/sass/views/_flux-monitor.scss
Labels: bug

#48 Setup react component test
  .editorconfig
  jest.config.js
  package.json
  src/web/app/reducer/index.ts
  src/web/app/views/tutorials/Tutorial-Controller.tsx
  src/web/app/widgets/List.spec.tsx
  src/web/app/widgets/List.tsx
  src/web/app/widgets/__snapshots__/List.spec.tsx.snap
  src/web/setupTests.ts
  src/web/tsconfig.json
  yarn.lock
Labels: enhancement

#49 Fix bugs about paste & paste in place shortcuts
  public/js/lib/svgeditor/svgcanvas.js
  src/web/app/actions/beambox/svg-editor.ts
Labels: bug

#53 Update calibrations messages
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/Camera-Calibration.tsx
  src/web/interfaces/ILang.d.ts
Labels: 1.6.1, enhancement

#52 Update menu-manager, Hide functions of non-beamo
  src/node/menu-manager.js
Labels: 1.6.1, enhancement

#55 Fix notarize & update CD related files
  .github/workflows/buildBS-linux.yml
  .github/workflows/buildBS-mac.yml
  .github/workflows/buildBS-win32.yml
  .github/workflows/buildBS-win64.yml
  requirements.txt
  scripts/notarize.js
Labels: 1.6.1, bug, enhancement

#56 Fix bugs in 1.6.1 alpha
  public/sass/views/_flux-monitor.scss
  src/web/app/views/settings/Setting-General.tsx
  src/web/main.ts
Labels: 1.6.1, bug

#60 Release/1.6.1 beta
  package.json
  src/web/app/views/dialogs/Change-Log.tsx
Labels: 1.6.1

#63 make jest support absolute path
  jest.config.js
Labels: enhancement

#66 Hotfix/v1.6.1b
  ihatewindowsCodeSign.js
  requirements.txt
  src/node/menu-manager.js
Labels: 1.6.1, bug

#77 1. add tests 2. fix stucked test caused by invoking window.location.reload()
  src/web/app/actions/windowLocation.ts
  src/web/app/app-settings.ts
  src/web/app/pages/Select-Connection-Type.spec.tsx
  src/web/app/pages/Select-Connection-Type.tsx
  src/web/app/pages/Settings.spec.tsx
  src/web/app/pages/Settings.tsx
  src/web/app/pages/__snapshots__/Settings.spec.tsx.snap
  src/web/app/views/settings/Setting-General.tsx
Labels: size/L

#75 Fix stamp blur computation bug and fit eslint rule
  src/web/helpers/jimp-helper.ts
Labels: size/L

#78 Update image sharpen using ghost opencv ws
  public/sass/views/_photo-edit-panel.scss
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/actions/dialog-caller.tsx
  src/web/app/actions/global-interaction.ts
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
  src/web/app/widgets/Button-Group.tsx
  src/web/app/widgets/Slider-Control.tsx
  src/web/helpers/api/open-cv.ts
  src/web/helpers/image-edit.ts
  src/web/helpers/jimp-helper.ts
  src/web/helpers/math/binomial-coefficient.spec.ts
  src/web/helpers/math/binomial-coefficient.ts
  src/web/helpers/math/gaussian-matrix.spec.ts
  src/web/helpers/math/gaussian-matrix.ts
  src/web/interfaces/IButton.d.ts
  src/web/interfaces/IImageData.d.ts
  src/web/interfaces/ILang.d.ts
Labels: size/XXL

#80 Fix windows disabled submenu clickable and Format _global.scss
  public/sass/core/_global.scss
Labels: size/XL
