Repository flux3dp/beam-studio, pull requests merged in 2021-05, with the labels that each got.

#82 add tests
  jest.config.js
  src/web/app/views/beambox/Image-Trace-Panel.tsx
  src/web/app/widgets/Slider-Control.spec.tsx
  src/web/app/widgets/Slider-Control.tsx
  src/web/app/widgets/Switch-Control.spec.tsx
  src/web/app/widgets/Switch-Control.tsx
  src/web/app/widgets/__snapshots__/Slider-Control.spec.tsx.snap
  src/web/app/widgets/__snapshots__/Switch-Control.spec.tsx.snap
Labels: size/XL

#81 Add image option operation to cmd history
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Image-Options.tsx
Labels: size/L

#83 Fix curve control singular bug in some condition
  src/web/app/widgets/Curve-Control.tsx
Labels: size/XL

#84 1.6.2 alpha
  package.json
Labels: size/XS

#67 Fix grouped elements angle calculation issue
  public/js/lib/svgeditor/svgcanvas.js
Labels: size/XS

#85 Close dialogs after getting into preference panel
  src/web/app/actions/dialog-caller.tsx
  src/web/app/actions/global-interaction.ts
  src/web/app/contexts/Dialog-Context.tsx
Labels: size/L

#88 move unit test check to the core due to code splitting
  .github/workflows/beam-studio-ci.yml
Labels: size/S

#89 Fix requireNode
  .eslintignore
  gulpfile.js
  package.json
  public/js/requireConfig.js
  webpack.config.js
  yarn.lock
Labels: size/XXL

#90 Add @types/react
  package.json
Labels: size/XS

#91 Format and add beambox style
  public/sass/pages/_beambox.scss
Labels: 1.6.2, enhancement

#93 move interface to core and leave electron store here
  .eslintrc.json
  gulpfile.js
  jest.config.js
  src/implementations/storage.ts
  src/tsconfig.json
  webpack.config.js
  yarn.lock
Labels: size/L

#92 Add sentry events
  electron-main.js
  src/node/deep-link-helper.js
Labels: 1.6.2, enhancement, size/M

#94 Update general settings style
  public/sass/pages/_settings.scss
Labels: size/XS

#87 Update workflow files
  .github/workflows/buildBS-linux.yml
  .github/workflows/buildBS-mac.yml
  .github/workflows/buildBS-win32.yml
  .github/workflows/buildBS-win64.yml
  build/clearup-develop-files.bat
  build/clearup-develop-files.sh
Labels: size/L

#95 Add Beam Studio api link to help menu
  src/node/menu-manager.js
  src/node/menu-resource.js
Labels: size/XXL

#96 Add Delete to edit menu
  src/node/menu-manager.js
  src/node/menu-resource.js
Labels: size/S

#98 Add view menu anti-aliasing
  public/sass/pages/_settings.scss
  src/node/menu-manager.js
  src/node/menu-resource.js
Labels: 1.6.2, enhancement, size/S

#99 extract browser behavior
  package.json
  src/implementations/browser.ts
  yarn.lock
Labels: size/S

#100 Add translation excepts rating
  src/node/menu-resource.js
Labels: size/S

#101 Add rating panel css and resource
  public/img/ShakeHands.svg
  public/img/WhiteStar.svg
  public/img/YellowStar.svg
  public/sass/main.scss
  public/sass/views/_rating-panel.scss
Labels: size/L

#102 Add info icon css and source
  public/img/info.svg
  public/sass/pages/_settings.scss
Labels: size/M

#104 1.7.0 beta
  electron-main.js
  package.json
Labels: 1.7.0, size/XS

#105 Change cursor to pointer when hovering stars
  public/sass/views/_rating-panel.scss
Labels: size/XS

#106 Update change-log-dialog.scss
  public/sass/views/_change-log-dialog.scss
Labels: 1.7.0, enhancement, size/L

#109 Refactor svgedit history
  public/js/requireConfig.js
Labels: enhancement, size/S

#110 Fix src web link & spectron test script
  package.json
  src/web
  src/web/app/views/beambox/Zoom-Block/Zoom-Block.tsx~Add test prototype
Labels: bug, size/L

#112 Add sentry implemetation
  src/implementations/sentry.ts
Labels: size/XS

#114 Update webpack config
  webpack.config.js
Labels: size/XS

#113 move fs to desktop version
  src/implementations/fileSystem.ts
Labels: size/M

#115 implement electron dialog
  src/implementations/dialog.ts
Labels: size/M

#119 Fix MANAGE_ACCOUNT item enabled not changed
  src/node/menu-manager.js
Labels: bug, size/XS

#118 remove redux
  package.json
  yarn.lock
Labels: size/L

#120 move font-scanner implmentation
  src/implementations/fontScanner.ts
  webpack.config.js
Labels: size/S

#121 move jimp here
  src/implementations/imageProcessor.ts
Labels: size/S
