Repository flux3dp/beam-studio, pull requests merged in 2021-07, with the labels that each got.

#157 Add backend log close event handler
  electron-main.js
Labels: size/XL

#158 Update sentry and window codesign timeout
  ihatewindowsCodeSign.js
  package.json
  yarn.lock
Labels: size/L

#159 move checkOSVersion here
  src/implementations/beamboxInit.ts
Labels: size/M

#160 Fix 1.7.1 bugs
  .github/workflows/buildBS-win32.yml
  .github/workflows/buildBS-win64.yml
  src/main.ts
Labels: size/S

#161 Add sentry implementation
  src/implementations/sentry.ts
Labels: size/XS

#162 Fix image menu translations
  src/node/menu-resource.js
Labels: size/S

#163 Fix read recent beam file
  src/implementations/recentMenuUpdater.ts
Labels: size/S

#164 Remove select dependency
  public/js/requireConfig.js
Labels: size/XS

#165 Fix svgnest buttons zindex
  public/sass/components/_svg-nest-buttons.scss
Labels: size/XS

#166 Update menu translations
  src/node/menu-resource.js
Labels: size/S
