Repository flux3dp/beam-studio, pull requests merged in 2021-08, with the labels that each got.

#168 Update threshold slider style
  public/sass/layout/beambox/right-panel/_object-panel.scss
Labels: size/XS

#170 Fix svg nest buttons style
  public/sass/components/_svg-nest-buttons.scss
Labels: size/XS

#171 Path preview
  package.json
  public/img/Pause.svg
  public/img/Play.svg
  public/img/Stop.svg
  public/img/print-preview.svg
  public/sass/layout/__layout.scss
  public/sass/layout/_path-preview.scss
  public/sass/layout/_top-bar.scss
  public/sass/layout/beambox/_zoom-block.scss
  yarn.lock
Labels: size/L

#172 Update menu open handler
  src/implementations/customMenuActionProvider.ts
  src/implementations/dialog.ts
  src/main.ts
  src/node/main-window-entry.js
Labels: size/M

#173 Update path preview style
  public/sass/layout/_path-preview.scss
Labels: size/S

#175 Fix path preview
  public/img/path-preview.svg
  public/img/print-preview.svg
  public/sass/layout/_path-preview.scss
  public/sass/layout/_top-bar.scss
Labels: size/M

#176 Update path preview related style
  public/sass/layout/_path-preview.scss
  public/sass/layout/_top-bar.scss
Labels: size/M

#177 Update path preview style
  public/sass/layout/_path-preview.scss
Labels: size/XS

#178 Adjust path preview icon
  public/img/path-preview.svg
  public/sass/layout/_top-bar.scss
Labels: size/M

#179 Use customized react context menu
  package.json
  public/js/requireConfig.js
  public/sass/base/__base.scss
  public/sass/base/_context-menu.scss
  public/sass/layout/beambox/_svg-editor.scss
  public/sass/layout/beambox/_zoom-block.scss
  public/sass/layout/beambox/right-panel/_layer-panel.scss
  yarn.lock
Labels: size/L

#180 fix css
  public/sass/layout/beambox/right-panel/_layer-panel.scss
  public/sass/layout/beambox/right-panel/_right-panel.scss
Labels: size/XS

#181 Update layer panel style
  public/sass/layout/beambox/right-panel/_layer-panel.scss
Labels: size/XS

#182 Add hammer.js
  package.json
  yarn.lock
Labels: size/S

#183 Update path preview style for windows
  public/sass/layout/_top-bar.scss
Labels: size/S

#185 Add style
  public/sass/components/__components.scss
  public/sass/components/_media-tutorial.scss
Labels: size/M

#186 Fix file path missed
  src/implementations/dialog.ts
Labels: size/XS
