Repository flux3dp/beam-studio, pull requests merged in 2022-03, with the labels that each got.

#214 1.9.3 alpha
  .github/workflows/buildBS-win32.yml
  .github/workflows/buildBS-win64.yml
  package.json
  src/implementations/menu.ts
Labels: size/S

#216 Fix load recent file
  src/implementations/recentMenuUpdater.ts
Labels: size/XS

#220 Feature/spectron-laser-test
  test/features/editor/editor-tests.js
  test/features/editor/right-panels-test/laser-cut-parameter-test/add-parameter-test.js
  test/features/editor/right-panels-test/laser-cut-parameter-test/custom-parameter-list-test.js
  test/features/editor/right-panels-test/laser-cut-parameter-test/power-caption-test.js
  test/features/editor/right-panels-test/laser-cut-parameter-test/power-enter-text-test.js
  test/features/editor/right-panels-test/laser-cut-parameter-test/remove-speed-limit-test.js
  test/features/editor/right-panels-test/laser-cut-parameter-test/reset-parameter-test.js
  test/features/editor/right-panels-test/laser-cut-parameter-test/speed-caption-test.js
Labels: size/XL

#218 Feature/spectron-modify-action2
  test/features/editor/modify-action-test/group-test.js
  test/features/editor/modify-action-test/mirror-test.js
  test/features/editor/modify-action-test/offset-test.js
  test/features/editor/modify-action-test/union-test.js
Labels: size/L

#217 Feature/spectron-modify-action
  test/features/editor/editor-tests.js
  test/features/editor/modify-action-test/align-test.js
  test/features/editor/modify-action-test/array-test.js
  test/features/editor/modify-action-test/change-object-test.js
  test/features/editor/modify-action-test/decompose-path-test.js
  test/features/editor/modify-action-test/distribute-test.js
  test/features/editor/modify-action-test/group-layer-test.js
  test/util/utils.js
Labels: size/XXL
